[buildPlans.Iovevka]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Iovevka.variants.design]
one = "base-long-top-serif"
two = "straight-neck-serifless"
six = "closed-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "closed-contour"
zero = "tall-slashed"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
r = 'corner-hooked-serifless'
f = "serifless-crossbar-at-x-height"
k = "symmetric-connected-serifless"
u = "toothless-rounded-serifless"
w = "straight-flat-top-serifless"
capital-eszet = "rounded-serifless"
eszet = "traditional-descending-serifless"
lower-iota = "zshaped"
lower-xi = "rounded"
asterisk = "hex-low"
underscore = "above-baseline"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Iovevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iovevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Iovevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iovevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
