[buildPlans.IovevkaHookyRound]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IovevkaHookyRound.variants.design]
three = "flat-top-serifless"
eight = "two-circles"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
g = "single-storey-earless-rounded"
i = "hooky"
j = "hooky"
k = "symmetric-connected-serifless"
l = "hooky"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
t = "hookless"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
cyrl-em = "hanging-serifless"

[buildPlans.IovevkaHookyRound.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IovevkaHookyRound.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IovevkaHookyRound.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# normal

[buildPlans.Iovevka]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Iovevka.variants.design]
one = "base"
three = "flat-top-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
k = "symmetric-connected-serifless"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
cyrl-em = "hanging-serifless"

[buildPlans.Iovevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iovevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iovevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# IovevkaHooky

[buildPlans.IovevkaHooky]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IovevkaHooky.variants.design]
three = "flat-top-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
i = "hooky"
j = "hooky"
k = "symmetric-connected-serifless"
l = "hooky"
t = "hookless"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
cyrl-em = "hanging-serifless"

[buildPlans.IovevkaHooky.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IovevkaHooky.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IovevkaHooky.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# Iovevka-Medium

[buildPlans.IovevkaHookyMix]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IovevkaHookyMix.variants.design]
# one = "base"
three = "flat-top-serifless"
eight = "two-circles"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
# capital-m = "slanted-sides-hanging-serifless"
# capital-u = "toothless-corner-serifless"
# a = "double-storey-toothless-corner"
# b = "toothless-corner-serifless"
# d = "toothless-corner-serifless"
# g = "single-storey-earless-corner"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
i = "hooky"
j = "hooky"
k = "symmetric-connected-serifless"
l = "hooky"
t = "hookless"
# m = "earless-corner-double-arch-serifless"
# n = "earless-corner-straight-serifless"
# p = "earless-corner-serifless"
# q = "earless-corner-straight-serifless"
# r = "earless-corner-serifless"
u = "toothless-rounded-serifless"
# u = "toothless-corner-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "open"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
cyrl-em = "hanging-serifless"

[buildPlans.IovevkaHookyMix.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IovevkaHookyMix.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IovevkaHookyMix.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# Serif

[buildPlans.Serif]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Serif.variants.design]
one = "base"
two = "straight-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "upright-arched-serifed"
six = "open-contour"
seven = "bend-serifed-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-l = "motion-serifed"
capital-z = "straight-serifed-with-crossbar"
f = "serifed"
k = "symmetric-connected-serifless"
r = "serifed"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
z = "straight-serifed-with-crossbar"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
# paren = "large-contour"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Serif.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Serif.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Serif.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# Ubuntu

[buildPlans.Ubuntu]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Ubuntu.variants.design]
one = "base"
two = "straight-neck-serifless"
four = "closed-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-m = "slanted-sides-hanging-serifless"
capital-u = "toothless-corner-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "tailed"
g = "single-storey-earless-corner"
i = "hooky"
l = "zshaped"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
u = "toothless-corner-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.Ubuntu.ligations]
  inherits = "dlig"

[buildPlans.Ubuntu.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ubuntu.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Ubuntu.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

########################################
# Round

[buildPlans.Round]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Round.variants.design]
two = "straight-neck-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-w = "curly-serifless"
a = "double-storey-toothless-rounded"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
f = "tailed"
g = "single-storey-earless-rounded"
i = "hooky"
l = "hooky"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.Round.ligations]
  inherits = "dlig"

[buildPlans.Round.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Round.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Round.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

# number-sign = "slanted"