[buildPlans.Iovevka]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Iovevka.variants.design]
one = "base"
two = "straight-neck-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-connected-serifless"
a = "double-storey-toothless-rounded"
j = "serifless"
k = "symmetric-connected-serifless"
l = "zshaped"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
u = "toothless-corner-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted"
ampersand = "lower-open"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Iovevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iovevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iovevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
