[buildPlans.Iovevka]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Iovevka.metricOverride]
cap = 1000
ascender = 1000
xHeight = 618
accentWidth = 1
parenSize = 1000
accentClearance = 1
accentHeight = 1
accentStackOffset = 1

[buildPlans.Iovevka.variants.design]
one = "base"
two = "straight-neck-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
zero = "slashed-cutout"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-connected-serifless"
capital-m = "slanted-sides-hanging-serifless"
a = "double-storey-toothless-corner"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
g = "single-storey-earless-corner"
k = "symmetric-connected-serifless"
l = "zshaped"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
u = "toothless-rounded-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
lower-lambda = "tailed-turn"
cyrl-capital-u = "straight-turn-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
paren = "large-contour"
number-sign = "slanted"
ampersand = "lower-open"
at = "compact"
dollar = "interrupted"
cent = "bar-interrupted"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Iovevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iovevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iovevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
