[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss10"

    [buildPlans.IosevkaCustom.variants.design]
    one = "no-base"
    two = "curly-neck-serifed"
    three = "two-arcs"
    four = "semi-open-non-crossing-serifless"
    five = "upright-arched-serifless"
    six = "closed-contour"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "round-top-serifless"
    capital-b = "standard-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-k = "symmetric-touching-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-p = "closed-serifless"
    capital-q = "crossing"
    capital-r = "straight-serifless"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "curly-serifless"
    capital-w = "straight-vertical-sides-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    capital-z = "curly-serifless"
    a = "single-storey-earless-corner-tailed"
    b = "toothless-rounded-serifless"
    c = "serifless"
    d = "tailed-serifed"
    e = "rounded"
    f = "serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    i = "tailed-serifed"
    j = "diagonal-tailed-serifed"
    k = "straight-serifless"
    l = "serifed-diagonal-tailed"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "straight-serifless"
    p = "eared-motion-serifed"
    q = "diagonal-tailed-serifless"
    r = "serifless"
    s = "serifless"
    t = "bent-hook"
    u = "toothless-rounded-serifless"
    v = "curly-serifless"
    w = "straight-vertical-sides-serifless"
    x = "curly-serifless"
    y = "cursive-serifless"
    z = "curly-serifless"
    capital-eszet = "rounded-serifless"
    long-s = "bent-hook-tailed"
    eszet = "sulzbacher-tailed-serifless"
    lower-eth = "curly-bar"
    capital-thorn = "serifless"
    lower-thorn = "serifless"
    lower-alpha = "crossing"
    lower-beta = "standard"
    capital-gamma = "serifless"
    lower-gamma = "casual"
    capital-delta = "curly"
    lower-delta = "rounded"
    lower-iota = "tailed-serifed"
    capital-lambda = "curly-top-serifed"
    lower-lambda = "straight-turn"
    lower-mu = "toothless-rounded-serifless"
    lower-nu = "curly"
    lower-xi = "rounded"
    lower-pi = "tailed"
    lower-tau = "tailed"
    lower-upsilon = "casual-serifless"
    lower-phi = "neo-hellenic"
    lower-chi = "semi-chancery-curly-serifless"
    lower-psi = "flat-top-serifless"
    cyrl-a = "double-storey-toothless-corner"
    cyrl-ve = "standard-serifless"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ze = "serifless"
    cyrl-ze = "serifless"
    cyrl-capital-ka = "symmetric-connected-serifless"
    cyrl-ka = "symmetric-connected-serifless"
    cyrl-el = "straight"
    cyrl-em = "hanging-serifless"
    cyrl-capital-en = "serifless"
    cyrl-en = "tailed-serifless"
    cyrl-capital-er = "closed-serifless"
    cyrl-er = "eared-serifless"
    cyrl-capital-u = "straight-turn-serifless"
    cyrl-u = "straight-serifless"
    cyrl-ef = "serifless"
    cyrl-che = "standard"
    cyrl-yeri = "corner"
    cyrl-yery = "round-tailed"
    cyrl-capital-e = "serifless"
    cyrl-e = "serifless"
    cyrl-capital-ya = "straight-serifless"
    cyrl-ya = "straight-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    ascii-grave = "straight"
    ascii-single-quote = "straight"
    paren = "normal"
    brace = "curly-flat-boundary"
    guillemet = "straight"
    number-sign = "slanted-open"
    ampersand = "et-tailed"
    at = "fourfold"
    dollar = "open"
    cent = "open"
    percent = "rings-segmented-slash"
    bar = "natural-slope"
    question = "smooth"
    pilcrow = "high"
    partial-derivative = "straight-bar"
    micro-sign = "toothless-rounded-serifless"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.weights.Medium]
shape = 520
menu = 520
css = 520

[buildPlans.IosevkaCustom.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
