[buildPlans.Iovevka]
family = "Iovevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Iovevka.variants.design]
one = "base-long-top-serif"
two = "straight-neck-serifless"
three = "two-arcs"
four = "semi-open-serifless"
five = "upright-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "tall-slashed"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "symmetric-connected-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "straight"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-serifless"
h = "straight-serifless"
i = "serifed"
j = "serifed"
k = "symmetric-connected-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
capital-eszet = "rounded-serifless"
long-s = "bent-hook-serifless"
eszet = "traditional-descending-serifless"
lower-eth = "straight-bar"
capital-thorn = "serifless"
lower-thorn = "serifless"
lower-alpha = "crossing"
lower-beta = "standard"
capital-gamma = "serifless"
lower-gamma = "straight"
capital-delta = "straight"
lower-delta = "rounded"
lower-iota = "zshaped"
capital-lambda = "straight-serifless"
lower-lambda = "straight"
lower-mu = "toothless-rounded-serifless"
lower-nu = "straight"
lower-xi = "rounded"
lower-pi = "tailless"
lower-tau = "flat-tailed"
lower-upsilon = "straight-serifless"
lower-phi = "cursive"
lower-chi = "straight-serifless"
lower-psi = "serifless"
cyrl-a = "double-storey-serifless"
cyrl-ve = "standard-serifless"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-el = "straight"
cyrl-em = "hanging-serifless"
cyrl-capital-en = "serifless"
cyrl-en = "serifless"
cyrl-capital-er = "closed-serifless"
cyrl-er = "eared-serifless"
cyrl-capital-u = "straight-serifless"
cyrl-u = "straight-serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-yeri = "corner"
cyrl-yery = "corner"
cyrl-capital-e = "serifless"
cyrl-e = "serifless"
cyrl-capital-ya = "straight-serifless"
cyrl-ya = "straight-serifless"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "natural-slope"
question = "smooth"
pilcrow = "high"
partial-derivative = "straight-bar"
micro-sign = "toothed-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Iovevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iovevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Iovevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iovevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
