[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss11"

    [buildPlans.IosevkaCustom.variants.design]
    one = "base"
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "semi-open-non-crossing-serifless"
    five = "upright-flat-serifless"
    six = "closed-contour"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "dotted"
    capital-a = "straight-serifless"
    capital-b = "standard-serifless"
    capital-c = "serifless"
    capital-d = "standard-serifless"
    capital-e = "serifless"
    capital-f = "serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-h = "serifless"
    capital-i = "serifed"
    capital-j = "serifless"
    capital-k = "symmetric-touching-serifless"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-p = "closed-serifless"
    capital-q = "crossing"
    capital-r = "straight-serifless"
    capital-s = "serifless"
    capital-t = "serifless"
    capital-u = "toothless-rounded-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    c = "serifless"
    d = "toothed-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    i = "zshaped"
    j = "flat-hook-serifed"
    k = "symmetric-touching-serifless"
    l = "serifed-semi-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "serifless"
    s = "serifless"
    t = "flat-hook-short-neck2"
    u = "toothless-rounded-serifless"
    v = "straight-serifless"
    w = "straight-flat-top-serifless"
    x = "straight-serifless"
    y = "straight-turn-serifless"
    z = "straight-serifless"
    capital-eszet = "corner-serifless"
    long-s = "flat-hook-serifless"
    eszet = "sulzbacher-serifless"
    lower-eth = "straight-bar"
    capital-thorn = "serifless"
    lower-thorn = "serifless"
    lower-alpha = "crossing"
    lower-beta = "standard"
    capital-gamma = "serifless"
    lower-gamma = "straight"
    capital-delta = "straight"
    lower-delta = "flat-top"
    lower-iota = "serifed-flat-tailed"
    capital-lambda = "straight-serifless"
    lower-lambda = "straight-turn"
    lower-mu = "toothless-rounded-serifless"
    lower-nu = "straight"
    lower-xi = "flat-top"
    lower-pi = "tailed"
    lower-tau = "flat-tailed"
    lower-upsilon = "straight-serifless"
    lower-phi = "cursive"
    lower-chi = "straight-serifless"
    lower-psi = "flat-top-serifless"
    cyrl-a = "double-storey-toothless-rounded"
    cyrl-ve = "standard-serifless"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ze = "serifless"
    cyrl-ze = "serifless"
    cyrl-capital-ka = "symmetric-connected-serifless"
    cyrl-ka = "symmetric-connected-serifless"
    cyrl-el = "straight"
    cyrl-em = "hanging-serifless"
    cyrl-capital-en = "serifless"
    cyrl-en = "tailed-serifless"
    cyrl-capital-er = "closed-serifless"
    cyrl-er = "earless-rounded-serifless"
    cyrl-capital-u = "straight-serifless"
    cyrl-u = "straight-serifless"
    cyrl-ef = "serifless"
    cyrl-che = "tailed"
    cyrl-yeri = "corner"
    cyrl-yery = "round-tailed"
    cyrl-capital-e = "serifless"
    cyrl-e = "serifless"
    cyrl-capital-ya = "straight-serifless"
    cyrl-ya = "straight-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "high"
    caret = "medium"
    ascii-grave = "straight"
    ascii-single-quote = "straight"
    paren = "flat-arc"
    brace = "straight"
    guillemet = "straight"
    number-sign = "slanted"
    ampersand = "upper-open"
    at = "compact"
    dollar = "open"
    cent = "through"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "corner-flat-hooked"
    pilcrow = "high"
    partial-derivative = "straight-bar"
    micro-sign = "toothed-serifless"
    lig-ltgteq = "flat"
    lig-neq = "more-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
