name: build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: "null"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fontName: ["Iosevka", "IosevkaAile"]
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: iosevka

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: start
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttf-unhinted::IosevkaCustom


  

      
